@startuml

actor       Admin as A
participant "Admin Dashboard" as Dash
participant "Add ER Popup" as Popup
database    "ER Data" as DB


A -> Dash: Clicks Add ER
Dash -> A : Opens Popup to add ER
A -> Popup : Fills in data fields for new ER
A -> Popup : Clicks 


@enduml