@startuml plantuml

component Client {
    [GUI] as gui
}

component Server {
    portin HTTP

    () ERs
    () Users
    () Authenticate

    [UserController] as uc
    [ERController] as ec
    [AuthHandler] as auth
    [RequestHandler] as req
}

database Databases {
    [ER Database] as ed
    [User Database] as ud
    [Credentials Database] as cd
}

ec - ERs
uc - Users
auth - Authenticate

gui --> HTTP
HTTP --> req

req --> ERs
req --> Users
req --> Authenticate

ec --> ed
uc --> ud
auth --> cd