@startuml doctorCollaboration
hide empty description

Doctor --> __:VirtualERSystem__ : 1: login()
__:VirtualERSystem__ --> Doctor : 2: authenticationSuccess()
Doctor --> __:ERQueue__ : 3: ViewQueue()
__:ERQueue__ --> __:VirtualERSystem__ : 4: sendQueue()
__:VirtualERSystem__ --> Doctor : 5: displayQueue()
Doctor --> __:VirtualERSystem__ : 6: selectPatient()
__:VirtualERSystem__ --> __:PatientData__ : 7: retrieveData()
__:PatientData__ --> __:VirtualERSystem__ : 8: returnData()
__:VirtualERSystem__ --> Doctor : 9: displayPatientData()
Doctor --> __:PatientData__ : 10-1: updateCritical()
Doctor --> __:PatientData__ : 10-2: updateNonCritical()

@enduml
