@startuml collaborationPatient
hide empty description

PatientDashboard --> __:VirtualERSystem__  : 1: login()
__:VirtualERSystem__ --> PatientDashboard : 2: authenticationSuccess()
__:VirtualERSystem__ --> __:QuestionnaireService__ : 3: takeQuestionnaire()
__:QuestionnaireService__ --> __:VirtualERSystem__ : 4: sendResults()
__:VirtualERSystem__ --> __:PatientData__ : 5: saveResults()
__:VirtualERSystem__ --> PatientDashboard : 6: advisePatient()
__:VirtualERSystem__ --> __:EmergencyServices__ : 7: notifyIfCritical()

@enduml
