@startuml Deployment
node "Patient's Device" {
  [Web Browser] --> [Virtual ER Web App]
  [Web Browser] --> [Sever (node.js)]
  [Web Browser] --> [database]
}

node "Virtual ER Server" {
  [Questionnaire Service] --> [Database]
  [Real-time ER Status Service] --> [Database]
}

node "ER System" {
  [ER Queue] --> [Virtual ER Server]
  [Dashboard] --> [ER Queue]
}

[Patient's Device] --> [Virtual ER Server]
[Virtual ER Server] --> [ER System]
[Virtual ER Server] --> [Nurse Hotline]
[Virtual ER Server] --> [Emergency Services (911)]
@enduml